-- UpdateChatwootCredentials
--
-- [2026-05-21] SEGREDO REMOVIDO POR SEGURANÇA.
-- Esta migration antes continha uma chave de API do Chatwoot hardcoded, que foi
-- exposta em repositório público e portanto deve ser rotacionada. Credenciais de
-- integração NUNCA devem ficar em migrations — são configuradas por conta via
-- painel admin / variáveis de ambiente (tabela `accounts`).
--
-- O conteúdo original era um backfill one-time que já foi aplicado em produção.
-- Em bancos novos esta migration é um no-op (nenhuma conta existe neste ponto do
-- histórico de migrations). Mantida como no-op para preservar o histórico aplicado.
SELECT 1;
